//Action Types:
export const ALL_PRODUCT = 'ALL_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_TYPE = 'ADD_PRODUCT_TYPE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_TYPE = 'DELETE_PRODUCT_TYPE';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_TYPE = 'EDIT_PRODUCT_TYPE';
export const SEARCH_PRODUCT_BY_PRICE = 'SEARCH_PRODUCT_BY_PRICE';
export const FETCH_PRODUCT_TYPE = 'FETCH_PRODUCT_TYPE';